default_context:
  _pegasus_version: 2022.4.2
  author_name: TW
  ci: github_actions
  css_framework: bootstrap
  css_theme: default
  database: postgres
  deploy_platform: heroku_docker
  description: Quickly check your tax records for common mistakes.
  domain_name: https://crypto-tax-checker.herokuapp.com
  email: support@CryptoTaxChecker.com
  enable_google_login: y
  enable_twitter_login: y
  front_end_framework: react
  project_name: Crypto Tax Checker - Docker None
  project_slug: crypto_tax_checker
  stripe_payment_mode: both
  subscription_billing_model: default
  use_api_keys: n
  use_docker: y
  use_impersonation: n
  use_sentry: y
  use_subscriptions: y
  use_teams: n
